---
- name: Test grep
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Test for line
      lineinfile: 
         path: /home/ysurmd/ansible/module_test/test.txt
         line: b
         regexp: '[\t ]{0,}test'
      ignore_errors: yes
      register: test_lineinfile

    - name: Debug test_grep
      debug:
        msg: "{{ test_lineinfile }}"
